#!/bin/sh
#
# Shell script to show the OpenVPN status.
#
# Copyright 2016-2020, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

set -e

BASENAME=$(basename "${0}")

# Variables
__OPENVPN_DATA__="/data/openvpn"

# Configuration files
OPENVPN_STATUS="${__OPENVPN_DATA__}/openvpn.status"

# Usage
show_usage() {
  echo "Usage: ${BASENAME} [options]"
  echo "  options:"
  echo "    <none>"
}

# Check arguments
if [ $# -ne 0 ]; then
  show_usage
  exit 1
fi

# Show the status
if [ -f ${OPENVPN_STATUS} ]; then
  cat ${OPENVPN_STATUS}
else
  echo >&2 "  [ERROR] No OpenVPN status available."
  exit 2
fi

# All done
exit 0
